### ISSUE TITLE
Some kind of instructions would be helpful

### ISSUE THREAD

**Issue by mattbishop** [TimLuq/wsdl-to-ts#1]
I'd love to use your tool in a CLI setting but I don't see how to do so. Please add a few lines to the readme to explain how to use this tool.

**Comment by TimLuq** [comment]
I developed this as an internal tool for an one-off project at the company where I'm employed. I thought that I might as well make it OSS.

Nice to see that someone else has interest in it.

**Comment by mattbishop** [comment]
Oh yes. SOAP <-> GraphQL is a thing. Typescript is the right glue between them.

**Comment by TimLuq** [comment]
@mattbishop did you get the documentation you needed? Did you get the expected result, or something at least usable, for your application?

**Comment by mattbishop** [comment]
The readme is great! Thanks for taking the time to set it up.
