### ISSUE TITLE
"xs:string" instead of "string"

### ISSUE THREAD

**Issue by sosoba** [TimLuq/wsdl-to-ts#3]
Try:
wsdl-to-ts https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl.xsd

Result:

export interface ISprawdzCaptchaInput {
    /** xs:string(undefined) */
    pCaptcha: xs:string;
}

**Comment by kevipapo1** [comment]
Same issue using a WSDL file with:

```wsdl
<s:element name="ElementName" type="s:string" />
```

The generated TypeScript definition looks something like:

```ts
export interface MyInterface {
    ElementName: s:string;
}
```

**Comment by ugo-gagliardelli** [comment]
That happens with xsd:int that should be translated as number.
Also, when a wsdl operation has no input parameters, an empty interface is created in .ts file, that's marked as an error.

**Comment by TimLuq** [comment]
PR #6 is a partial fix for this issue. Most people have problems which should be taken care of.

The rest of the problems are harder to take care of such as the above mentioned `xs:int -> number`, since this would require an exhaustive list of type  translations.

Regarding empty interfaces; they are a bad practice but not disallowed by TypeScript. If they are allowed or not is dependent on your tslint configuration for that project. What should be done is turn off that check in the generated files in the same way I've disables the check for max line lengths, please open a separate issue for this.

**Comment by gitowiec** [comment]
What's with this issue? I generated typescript file which is useless because of types prefixed with `xsd:`

**Comment by sosoba** [comment]
Dziękuję za wiadomość. Do 25.06.2018 będę przebywał na urlopie. W sprawach nie cierpiących zwłoki proszę o kontakt z Markiem Michalskim tel. 32-757-4351, email: marek.michalski@coig.pl.
  
  
  
  Sławomir Osoba
Lider Zespołu Z07

tel. (+48) 32 757 4192
tel. kom. (+48) 609 793 920
slawomir.osoba@coig.pl

 	 		 				 COIG S.A. | ul. Mikołowska 100, 40-065 Katowice | coig@coig.pl | www.coig.pl	  		 
  			Sąd Rejonowy Katowice-Wschód w Katowicach
			VIII Wydział Gospodarczy Krajowego Rejestru Sądowego KRS 0000092497,
			Kapitał zakładowy w kwocie: 5.400.000 zł, w całości wniesiony. NIP: 634-013-4205	  		

Dokument ten zawiera informacje poufne, które mogą być również objęte tajemnicą służbową. Jest on przeznaczony do wyłącznego użytku adresata.
Jeśli nie są Państwo jego adresatem, to wszelkie rozpowszechnianie, dystrybucja, reprodukcja, kopiowanie, publikacja lub wykorzystanie tego dokumentu lub informacji jest zabronione. Jeśli otrzymali Państwo tą wiadomość przez pomyłkę, prosimy o bezzwłoczne skontaktowanie się z nami oraz usunięcie wiadomości z Państwa komputera.  

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail by mistake) please notify the sender immediately and destroy this email. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

**Comment by ghost** [comment]
> The rest of the problems are harder to take care of such as the above mentioned `xs:int -> number`, since this would require an exhaustive list of type translations.

Is there any plan in doing this ? Because right now i'm having wsdl converted in "ts" which contains both 'int', 'long', 'bool' and arrays that seems to be buggy (i got 4 fields looking like : name : string**>**; ).

Thanks for your help :)
